language: node_js
node_js:
  - "7.0"
script:
  - echo "Deploying"
  - npm install
  - ng build
install:
  - npm install -g firebase-tools @angular/cli
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master